# -*- coding: utf-8 -*-
"""AUTHORIZE combo strategy to PAPER PRODUCTION.
registry: production_strategy=COMBO_SMC_EVENT, buy_enabled=true, state=PAPER_PRODUCTION.
Paper tracking only (no real money): BUY_VALID generated by daily scanner, tracked in paper_trades."""
import json, io, sys, datetime

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
p = r"E:\test\smc_project\hermes\smc_monitor\production_registry.json"
d = json.load(open(p, encoding="utf-8"))

d["state"] = "PAPER_PRODUCTION_COMBO"
d["production_strategy"] = "COMBO_SMC_EVENT"
d["buy_enabled"] = True
d["authorization"] = {
    "mode": "PAPER_PRODUCTION",
    "authorized_at": datetime.date.today().isoformat(),
    "note": "用户授权组合策略进入准生产（纸面跟踪）：BUY_VALID 由每日 scanner 产生，记录纸面持仓与盈亏，不涉及真实资金。",
    "real_money": False,
}
d["research_candidates"]["COMBO_SMC_EVENT"].update({
    "status": "PAPER_PRODUCTION",
    "production_authorized": True,
    "buy_enabled": True,
    "authorized_at": datetime.date.today().isoformat(),
    "mode": "paper_tracking",
})

with open(p, "w", encoding="utf-8") as fh:
    json.dump(d, fh, ensure_ascii=False, indent=2)
print("registry updated:")
print("  state:", d["state"])
print("  strategy:", d["production_strategy"], "| buy_enabled:", d["buy_enabled"])
